sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
env:
before_install:
  - export LD_LIBRARY_PATH=.:`cat /etc/ld.so.conf.d/* | grep -vF "#" | tr "\\n" ":" | sed -e "s/:$//g"`
  - sudo add-apt-repository -y ppa:kevinkreiser/prime-server
  - sudo add-apt-repository -y ppa:valhalla-routing/valhalla
  - sudo apt-get update
install:
  - sudo apt-get install -y -qq autoconf automake libtool make gcc g++ lcov libvalhalla-dev valhalla-bin
before_script:
script:
  ./autogen.sh && ./configure --enable-coverage && make test -j$(nproc)
after_failure:
  - cat config.log
  - cat test/*.log
